[package]
name = "usysconf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-process = "2.5.0"
bincode = "3.0.0"
clap = "4.5.54"
dag = { git = "https://github.com/serpent-os/moss-rs.git", version = "0.1.0" }
futures = "0.3.31"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
thiserror = "2.0.17"

[[bin]]
name = "usysconf"
path = "src/bin/usysconf/main.rs"
